		</div>
	</div>
	<footer id="footer">
		<div class="wrap">
			<a href="http://context.io"><div id="contextio">Powered by Context.IO</div></a>
			<hr />
			<nav>
				<ul>
					<li><a href="http://context.io/terms-of-service" target="_blank">Terms</a></li>
					<li><a href="http://context.io/privacy" target="_blank">Privacy</a></li>
					<li class="right">EmailToBox &copy; <?php echo date('Y'); ?></li>
				</ul>
			</nav>
		</div>
	</footer>
</body>
</html>