<?php include('header.phtml'); ?>
			
	<header>
		<h1 class="center">Drag and Drop Integration Between Email and Box</h1>
	</header>
	<section id="homepage-graphic" class="box">
		<ul>
			<li class="left">Whatever you put here ...</li>
			<li class="right">... is automatically uploaded here</li>
		</ul>
		<img src="/images/sync-graphic.jpg" width="908" height="201" alt="Sync Graphic">
	</section>
	
	<section id="small-boxes">
		<div class="box">
			<h3>Simple to Use</h3>
			<p>Drag and drop emails into the EmailToBox folder and we'll do the rest.</p>
		</div>
		<div class="box">
			<h3>Track Revisions</h3>
			<p>EmailToBox is smart. It will automatically save new versions of files it recognizes.</p>
		</div>
		<div class="box last">
			<h3>The Power of Box</h3>
			<p>Take advantage of Box.net's powerful cloud storage capabilities.</p>
		</div>
		<div class="clear">
	</section>
	
	<section id="get-started" class="center">
		<a href="/signup">Get Started Now</a>
		<h2>Works with Gmail or any IMAP email account</h2>
	</section>

<?php include('footer.phtml'); ?>