<?php include('header.phtml'); ?>

<div class="center">
	
	<div id="signup-steps">
		<nav class="step-1"></nav>
		<ul>
			<li class="active">Connect <span>Box Account</span></li>
			<li>Connect <span>Email Account</span></li>
			<li>Start Saving <span>Attachments</span></li>
		</ul>
	</div>
	
	<hr />
	
	<header>
		<h1>Connect Your Box Account</h1>
		<h3>Click the button below to open a new window and login to Box.net.</h3>
	</header>
	<div id="signup"><a href="/signup/box" class="button">Connect To Box</a></div>
</div>

<?php include('footer.phtml'); ?>